FROM python:3.10-slim
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential libffi-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir --upgrade pip

WORKDIR /bot

COPY shared/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY bot/ .
COPY shared /bot/shared
WORKDIR /bot


CMD [ "python3", "-u", "main.py"]