services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    volumes:
      - ./data:/app/data
    env_file:
      - .env
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    env_file:
      - .env
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_ROOT_NAME}
    volumes:
      - ./docker/mongo/mongodump:/mongodump
      - ./docker/mongo/data:/data/db
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    command: mongod --quiet --logpath /dev/null --logappend
    logging:
      driver: "none"
    env_file:
      - .env
  redis:
    image: redis:latest
    restart: always
    command: --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:${REDIS_PORT}
    env_file:
      - .env
