FROM python:3.10-slim
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential libffi-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir --upgrade pip

WORKDIR /worker

COPY shared/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY worker/ .
COPY shared /worker/shared

WORKDIR /worker

CMD [ "python3", "-u", "main.py"]